version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3001:3000"  # แก้ไขพอร์ตที่ใช้บนเครื่องโฮสต์เป็น 3001

  server:
    build: ./server
    ports:
      - "5000:5000"

  model:
    build: ./model
